### ISSUE TITLE
Error Using HACS

### ISSUE THREAD

**Issue by charlievogt** [widewing/ha-toyota-na#15]
Once I log into the integration with my Toyota credentials, it appears in the GUI that it was successful, though no entities or devices are added.  The logs show several errors, included below.

Any suggestions?  I saw another issue with similar logs, and the indication seemed to be that the vehicle was too old to work.  This is a 2020 Highlander.

```
2022-01-22 11:24:37 WARNING (MainThread) [custom_components.toyota_na] Error fetching vehicle status
2022-01-22 11:24:37 WARNING (MainThread) [custom_components.toyota_na] Error fetching vehicle health status
2022-01-22 11:24:38 ERROR (MainThread) [root] Error parsing response: {"status":"SUCCESS","code":200,"message":"Ok","errors":[]}
2022-01-22 11:24:38 WARNING (MainThread) [custom_components.toyota_na] Error fetching odometer detail
2022-01-22 11:24:38 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up toyota_na platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/toyota_na/sensor.py", line 31, in async_setup_entry
if sensor.available:
File "/config/custom_components/toyota_na/sensor.py", line 75, in available
return "fuelLevel" in self.vehicle_odometer_detail
File "/config/custom_components/toyota_na/base_entity.py", line 47, in vehicle_odometer_detail
return self.vehicle["odometer_detail"]
KeyError: 'odometer_detail'
2022-01-22 11:24:38 ERROR (MainThread) [homeassistant.components.device_tracker] Error while setting up toyota_na platform for device_tracker
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/toyota_na/device_tracker.py", line 21, in async_setup_entry
if tracker.available:
File "/config/custom_components/toyota_na/device_tracker.py", line 47, in available
return "latitude" in self.vehicle_status
File "/config/custom_components/toyota_na/base_entity.py", line 35, in vehicle_status
return self.vehicle["status"]
KeyError: 'status'

```

**Comment by vanstinator** [comment]
Are you subscribed to `remote services`?

**Comment by widewing** [comment]
We just started The with on supporting older generations here https://github.com/widewing/toyota-na/pull/4
And a related issue: https://github.com/widewing/toyota-na/issues/2

**Comment by charlievogt** [comment]
I am subscribed to remote services.  I am able to do everything from the Toyota app.

**Comment by bwalshin** [comment]
I'm seeing the same issues. I have a 2020 Corolla XSE and I'm subscribed to remote services. Not sure why it won't read my car.

**Comment by nmbgeek** [comment]
Similar issues here:
`Logger: root
Source: /usr/local/lib/python3.9/site-packages/toyota_na/client.py:34
First occurred: February 1, 2022, 9:28:27 PM (1 occurrences)
Last logged: February 1, 2022, 9:28:27 PM

Error parsing response: {"status":"SUCCESS","code":200,"message":"Ok","errors":[]}
`-`
2022-02-02 21:13:56 WARNING (MainThread) [custom_components.toyota_na] Error fetching vehicle status
2022-02-02 21:13:57 ERROR (MainThread) [root] Error parsing response: {"status":"SUCCESS","code":200,"message":"Ok","errors":[]}
2022-02-02 21:13:57 WARNING (MainThread) [custom_components.toyota_na] Error fetching odometer detail
2022-02-02 21:13:57 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up toyota_na platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/toyota_na/sensor.py", line 31, in async_setup_entry
    if sensor.available:
  File "/config/custom_components/toyota_na/sensor.py", line 75, in available
    return "fuelLevel" in self.vehicle_odometer_detail
  File "/config/custom_components/toyota_na/base_entity.py", line 47, in vehicle_odometer_detail
    return self.vehicle["odometer_detail"]
KeyError: 'odometer_detail'
2022-02-02 21:13:57 ERROR (MainThread) [homeassistant.components.device_tracker] Error while setting up toyota_na platform for device_tracker
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/toyota_na/device_tracker.py", line 21, in async_setup_entry
    if tracker.available:
  File "/config/custom_components/toyota_na/device_tracker.py", line 47, in available
    return "latitude" in self.vehicle_status
  File "/config/custom_components/toyota_na/base_entity.py", line 35, in vehicle_status
    return self.vehicle["status"]
KeyError: 'status'`

**Comment by vanstinator** [comment]
Can you try again on https://github.com/widewing/ha-toyota-na/releases/tag/v2.0.0

We fixed several bugs and implemented support for some Entune 3 vehicles that previously errored out like this.

**Comment by charlievogt** [comment]
Thanks!  I tried again, but am now receiving a new set of errors.

"Retrying setup: None is not a valid ApiVehicleGeneration" shows up on the integrations page of HA.

These two events are in the logs:

'''
Logger: homeassistant.config_entries
Source: config_entries.py:366 
First occurred: 12:51:51 PM (3 occurrences) 
Last logged: 12:56:32 PM

Config entry 'leah.charlie.vogt@gmail.com' for toyota_na integration not ready yet: None is not a valid ApiVehicleGeneration; Retrying in background
'''

'''
This error originated from a custom integration.

Logger: custom_components.toyota_na
Source: custom_components/toyota_na/__init__.py:104 
Integration: Toyota (North America) (documentation, issues) 
First occurred: 12:51:51 PM (17 occurrences) 
Last logged: 12:57:54 PM

Error fetching data
Traceback (most recent call last):
  File "/config/custom_components/toyota_na/__init__.py", line 104, in update_vehicles_status
    raw_vehicles = await get_vehicles(client)
  File "/usr/local/lib/python3.9/site-packages/toyota_na/vehicle/vehicle.py", line 14, in get_vehicles
    ApiVehicleGeneration(vehicle["generation"])
  File "/usr/local/lib/python3.9/enum.py", line 384, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.9/enum.py", line 702, in __new__
    raise ve_exc
ValueError: None is not a valid ApiVehicleGeneration
'''

**Comment by vanstinator** [comment]
We just pushed a release that supports the diagnostic platform in HA. Navigate to the integrations page, select the menu on the `Toyota` integration, and click `Download Diagnostics`. The dump automatically redacts all sensitive information and will provide us with a lot more detail to help diagnose what's going on here.

**Comment by dkmcgowan** [comment]
This would likely be an issue with the base library for older vehicles, open a new issue if still happening
